//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int Id { get; set; }
        public string Documento_Identidad { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public string Correo_Electronico { get; set; }
        public string Correo_Electronico2 { get; set; }
        public string Direccion_Fisica { get; set; }
        public string Direccion_Fisica2 { get; set; }
    }
}
