//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaNET.Servicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/Service.Model")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_ElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_Electronico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direccion_FisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direccion_Fisica2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Documento_IdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_NacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_Electronico {
            get {
                return this.Correo_ElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_ElectronicoField, value) != true)) {
                    this.Correo_ElectronicoField = value;
                    this.RaisePropertyChanged("Correo_Electronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_Electronico2 {
            get {
                return this.Correo_Electronico2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_Electronico2Field, value) != true)) {
                    this.Correo_Electronico2Field = value;
                    this.RaisePropertyChanged("Correo_Electronico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion_Fisica {
            get {
                return this.Direccion_FisicaField;
            }
            set {
                if ((object.ReferenceEquals(this.Direccion_FisicaField, value) != true)) {
                    this.Direccion_FisicaField = value;
                    this.RaisePropertyChanged("Direccion_Fisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion_Fisica2 {
            get {
                return this.Direccion_Fisica2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Direccion_Fisica2Field, value) != true)) {
                    this.Direccion_Fisica2Field = value;
                    this.RaisePropertyChanged("Direccion_Fisica2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento_Identidad {
            get {
                return this.Documento_IdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.Documento_IdentidadField, value) != true)) {
                    this.Documento_IdentidadField = value;
                    this.RaisePropertyChanged("Documento_Identidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Nacimiento {
            get {
                return this.Fecha_NacimientoField;
            }
            set {
                if ((this.Fecha_NacimientoField.Equals(value) != true)) {
                    this.Fecha_NacimientoField = value;
                    this.RaisePropertyChanged("Fecha_Nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono2 {
            get {
                return this.Telefono2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono2Field, value) != true)) {
                    this.Telefono2Field = value;
                    this.RaisePropertyChanged("Telefono2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Consultar", ReplyAction="http://tempuri.org/IService1/ConsultarResponse")]
        PruebaNET.Servicio.Persona[] Consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Consultar", ReplyAction="http://tempuri.org/IService1/ConsultarResponse")]
        System.Threading.Tasks.Task<PruebaNET.Servicio.Persona[]> ConsultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Adicionar", ReplyAction="http://tempuri.org/IService1/AdicionarResponse")]
        bool Adicionar(PruebaNET.Servicio.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Adicionar", ReplyAction="http://tempuri.org/IService1/AdicionarResponse")]
        System.Threading.Tasks.Task<bool> AdicionarAsync(PruebaNET.Servicio.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarIdentificacion", ReplyAction="http://tempuri.org/IService1/ConsultarIdentificacionResponse")]
        bool ConsultarIdentificacion(string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultarIdentificacion", ReplyAction="http://tempuri.org/IService1/ConsultarIdentificacionResponse")]
        System.Threading.Tasks.Task<bool> ConsultarIdentificacionAsync(string identificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PruebaNET.Servicio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PruebaNET.Servicio.IService1>, PruebaNET.Servicio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PruebaNET.Servicio.Persona[] Consultar() {
            return base.Channel.Consultar();
        }
        
        public System.Threading.Tasks.Task<PruebaNET.Servicio.Persona[]> ConsultarAsync() {
            return base.Channel.ConsultarAsync();
        }
        
        public bool Adicionar(PruebaNET.Servicio.Persona persona) {
            return base.Channel.Adicionar(persona);
        }
        
        public System.Threading.Tasks.Task<bool> AdicionarAsync(PruebaNET.Servicio.Persona persona) {
            return base.Channel.AdicionarAsync(persona);
        }
        
        public bool ConsultarIdentificacion(string identificacion) {
            return base.Channel.ConsultarIdentificacion(identificacion);
        }
        
        public System.Threading.Tasks.Task<bool> ConsultarIdentificacionAsync(string identificacion) {
            return base.Channel.ConsultarIdentificacionAsync(identificacion);
        }
    }
}
